target-version = "py312"
line-length = 88

[lint]
select = ["E", "F", "I", "UP", "B", "SIM", "ASYNC"]
ignore = ["E501"]

[lint.per-file-ignores]
"tests/*" = ["B011"]
"ai_engineer/*" = ["E402", "T201"]
