blank_issues_enabled: false
contact_links:
  - name: DOT-NL Chargers Discussions
    url: https://github.com/DonTranQuiL/DOT-NL-Chargers-for-Home-Assistant/issues
    about: Ask questions and share ideas about DOT-NL Chargers.
